name: BungeeServerAdmin
version: 1.4
authors: [TGamesTV, DavidoTek]
main: de.mfgames.BungeeServerManager.BungeeServerManager

commands:
  bungeeserveradmin:
    description: BungeeServerAdmin Command
    aliases: bsa
  bungeeserverstats:
    description: Show statistics / system usage
    aliases: bss