name: BungeeServerAdmin
version: 1.0
authors: [TGamesTV, DavidoTek]
main: de.mfgames.BungeeServerManager.BungeeServerManager

commands:
  bungeeserveradmin:
    description: BungeeServerAdmin Command
    aliases: bsa