name: BungeeServerManager
version: 1.0
authors: [TGamesTV, DavidoTek]
main: de.mfgames.BungeeServerManager.BungeeServerManager

commands:
  bungeeservermanager:
    description: BungeeServerManager Command
    aliases: bsm